<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   TimVroom
 * @package    Timvroom_Custompdf
 * @copyright  Copyright (c) 2014 - Nichecommerce (http://www.nichecommerce.nl)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<h1><?php echo $this->helper('custompdf')->getPdfTitle(); ?></h1>
<label><?php echo $this->__('Delivery to');?>:</label>
<address>
    <?php $shippingAddress = $this->getShippingAddress(); ?>
    <span class="label"><?php echo $this->__('Customer Name');?>: </span><?php echo $shippingAddress->getName(); ?><br/>
    <span class="label"><?php echo $this->__('Address');?>: </span><?php echo $shippingAddress->getStreetFull(); ?><br/>
    <span
        class="label"><?php echo $this->__('Postcode');?>: </span><?php echo $shippingAddress->getPostcode(); ?> <?php echo $shippingAddress->getCity(); ?>
    <br/>
</address>

<table class="data-table info-table">
    <tr>
        <th class="col-1"><?php $this->__('Pakbonnummer'); ?></th>
        <td class="col-2"><?php $this->getShipment()->getIncrementId(); ?></td>
        <th class="col-3"><?php echo $this->__('Billing name'); ?></th>
        <td class="col-4">: <?php echo $this->getBillingAddress()->getName(); ?></td>
    </tr>
    <tr>
        <th class="col-1"><?php echo $this->__('Delivery date'); ?></th>
        <td class="col-2">:</td>
        <th class="col-3"><?php echo $this->__('Shipping method'); ?></th>
        <td class="col-4">: <?php echo $this->getOrder()->getShippingDescription(); ?></td>
    </tr>
    <tr>
        <th class="col-1"><?php echo $this->__('Order #'); ?></th>
        <td class="col-2">: <?php echo $this->getOrder()->getIncrementId(); ?></td>
        <th class="col-3"><?php echo $this->__('Payment method'); ?></th>
        <td class="col-4">: <?php echo $this->getOrder()->getPayment()->getMethodInstance()->getTitle(); ?></td>
    </tr>
</table>

<hr/>
<div class="content-block">
    <?php echo $this->getChildHtml('items', false); ?>
    <div class="totals clearfix">
        <table class=totals-table>
            <colgroup>
                <col />
                <col width="1" />
            </colgroup>
            <tbody>
                <?php echo $this->getChild('order_totals')->reset()->toHtml(); ?>
            </tbody>
        </table>
    </div>
</div>
