<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   TimVroom
 * @package    Timvroom_Custompdf
 * @copyright  Copyright (c) 2014 - Nichecommerce (http://www.nichecommerce.nl)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (count($this->getItems()) > 0): ?>
    <div class="products">
        <table class="data-table products-table">
            <thead>
            <tr>
                <th class="col-1"><?php echo $this->__('Item'); ?></th>
                <th class="col-2"><?php echo $this->__('Sku'); ?></th>
                <th class="col-3"><?php echo $this->__('Qty ordered'); ?></th>
                <th class="col-4"><?php echo $this->__('Qty delivered'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->getItems() as $item): ?>
                <?php echo $this->getItemHtml($item); ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;