<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   TimVroom
 * @package    Timvroom_Custompdf
 * @copyright  Copyright (c) 2014 - Nichecommerce (http://www.nichecommerce.nl)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang=<?php echo $this->getLang(); ?> id="top" class="">
<head>
    <?php echo $this->getChildHtml('head'); ?>
</head>
<body class="page-pdf<?php echo $this->getBodyClass() ? $this->getBodyClass() : '' ?>">
<?php if ($this->getObjects()) :
    $size    = $this->getObjects()->getSize();
    $i       = 0;
    $storeId = 0;
    $appEmulation = Mage::getSingleton('core/app_emulation');
    foreach ($this->getObjects() as $object):
        if ($object->getStoreId()) {
            $storeId = $object->getStoreId();
            $initialEnvironmentInfo = $appEmulation->startEnvironmentEmulation($storeId);
        }
        if (Mage::registry('current_object')){
            Mage::unregister('current_object');
        }
        Mage::register('current_object', $object);
        ?>
        <script type="text/php">
            if (isset($pdf)) {
                $cpdf = $pdf->get_cpdf();
                $cpdf->objects[$cpdf->currentPage]['info']['newPage'] = true;
            }
        </script>
        <div class="<?php if (++$i < $size) { ?>pagebreak<?php } ?> newdoc">
            <div class="pdf-head">
                <?php $logoSrc = Mage::getStoreConfig('design/header/logo_src', $storeId); ?>
                <img
                    src="<?php echo $this->getSkinUrl($logoSrc) ? $this->getSkinUrl($logoSrc) : $this->getSkinUrl('images/logo_print.gif') ?>"
                    class="logo" alt=""/>
            </div>
            <?php echo $this->getChildHtml('content', false) ?>
            <?php echo $this->getChildHtml('footer', false) ?>
        </div>
    <?php endforeach;
endif;?>
<?php
if ($object->getStoreId()) {
    $appEmulation->stopEnvironmentEmulation($initialEnvironmentInfo);
}?>
</body>
</html>
