<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   TimVroom
 * @package    Timvroom_Custompdf
 * @copyright  Copyright (c) 2014 - Nichecommerce (http://www.nichecommerce.nl)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<hr />
<div class="confirmation">
    <span class="small"><?php echo $this->__('Received for approval');?></span>

    <div class="fieldset">
        <div class="field field-name">
            <label><?php echo $this->__('Date delivered');?>:</label>
            <div class="dotted-line"></div>
        </div>
        <div class="field field-name">
            <label><?php echo $this->__('Name');?>:</label>
            <div class="dotted-line"></div>
        </div>
        <div class="field field-signature">
            <label><?php echo $this->__('Signature');?>:</label>
            <div class="dotted-line"></div>
        </div>
    </div>
</div>
