<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   TimVroom
 * @package    Timvroom_Custompdf
 * @copyright  Copyright (c) 2014 - Nichecommerce (http://www.nichecommerce.nl)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$_item = $this->getItem();
$end = 1;
?>
<tr>
    <td class="col-1">
        <span class="product-name"><?php echo $_item->getName();?></span>
        <?php if ($_options = $this->getOptionList()):?>
            <dl class="item-options">
                <?php foreach ($_options as $_option) : ?>
                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                    <dd>
                        <?php echo $this->escapeHtml($_option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif;?>
    </td>
    <td class="col-2">
        <?php echo $_item->getSku();?>
    </td>
    <td class="col-3">
        <?php if($colli = $_item->getProduct()->getData('nc_colli')):?>
            <?php echo ((int)$colli * (int)$_item->getQtyShipped());?>
        <?php endif;?>
    </td>
    <td class="col-4">
        <?php echo (int)$_item->getQtyShipped();?>
    </td>
    <td class="col-5"></td>
</tr>